os:
  - linux
  - osx

git:
  depth: 10

notifications:
  email: false

sudo: false

language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

env:
  - CC=clang CXX=clang++ npm_config_clang=1

script: npm test

branches:
  only:
    - master
