image: Visual Studio 2015

environment:
  matrix:
  - nodejs_version: "12"

platform:
  - x64

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install

build_script:
  - npm test
  - npm run prebuild-node
  - npm run prebuild-node-ia32
  - npm run prebuild-electron
  - npm run prebuild-electron-ia32
  - if defined APPVEYOR_REPO_TAG_NAME (npm run upload)

build: off

branches:
  only:
    - master
