image: Visual Studio 2015

environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "10"
  - nodejs_version: "11"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

branches:
  only:
    - master
