image: Visual Studio 2015

environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "10"
  - nodejs_version: "11"
  - nodejs_version: "12"

platform:
  - x86
  - x64

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

branches:
  only:
    - master
